container:
  image: gradle:jdk8

check_task:
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script:
      - echo $GRADLE_VERSION
      - cat dependencies.json
    reupload_on_changes: false
  check_script: gradle check
  always:
    junit_result_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit
      type: text/xml
